// GENERATED from pkg/errfile — run scripts/sync-errfile.sh
// Package errfile writes every fault a Go process in this repo sees to ONE append-only, rotating,
// operator-local file: ~/T/ezbookkeeping/error.err (pm/error_err.mdx). It is stdlib only, so it
// sits below every other package and can be vendored byte-for-byte into the CLI's module
// (cli/internal/errfile, regenerated by scripts/sync-errfile.sh).
//
// The call-site API (§6.1) — one short line per error site, nothing declared per file:
//
//	errfile.Caught(doing, err, fields...)     // ERROR  → error.err
//	errfile.Warn(doing, err, fields...)       // WARN   → error.err
//	errfile.Expected(doing, err)              // nothing (EZBK_ERROR_FILE_VERBOSE=1: EXPECTED)
//	errfile.Fatal(doing, err, fields...)      // FATAL + synchronous flush; never exits
//	errfile.Recovered(doing, rec, fields...)  // ERROR with the panic stack; never re-panics
//	errfile.Go(doing, fn)                     // go fn() under a recover net
//	defer errfile.RecoverNet(doing)()         // the same net for a plain `go` statement
//	errfile.F(key, value)                     // an allowlisted, redacted data field
//	errfile.Describe(err)                     // "Type: message | cause: …" for code that must SHOW a message
//	errfile.IsReported(err)                   // has this value (or anything it wraps) been written?
//	errfile.Flush()                           // synchronous barrier
//	errfile.Install(errfile.Options{App: "server"})
//
// `where` comes from runtime.Caller, on the error path only, as a repo-relative file.go:line.
//
// The eight Go patterns (§7), in brief:
//
//	G1  if err != nil { errfile.Caught("counting the accounts", err); return nil, errs.ErrX }
//	G2  if err != nil { return nil, err }                       // handed on: no call needed
//	G3  if err != nil { errfile.Expected("reading the optional file", err); return def }
//	G4  _ = os.Remove(p)   or   if err := os.Remove(p); err != nil { errfile.Warn("…", err) }
//	G5  if r := recover(); r != nil { errfile.Recovered("running ezbk", r); … }
//	G6  errfile.Go("sending the verification email", func() { … })
//	G7  central nets: gin recovery, machine wrap(), cron doRun — wired once
//	G8  errfile.Fatal("running ezbookkeeping", err); log.Fatalf(…)
//
// Everything the library does is total: it never panics into its caller, never recurses into
// itself, never logs through pkg/log, and never does synchronous filesystem work on a request path
// (the only synchronous writes are Flush, Fatal and the exit/signal flush).
package errfile
