#!/usr/bin/env node
/**
 * Generate src/instructions.ts from ../ai/mcp_prompt_ezbookkeeping.md — pm/mcp.mdx §8.3 (LOCKED).
 *
 * The prompt is prose at the repo top level (a second consumer may share it). This script reads it,
 * refuses an absent or empty file (a build that cannot find the prompt FAILS; it never falls back
 * to a default string), refuses any `{TOKEN}` that is not in the closed map (naming it), and writes
 * the prose into src/instructions.ts. Counts and paths are substituted at startup from the registry
 * and the config (src/prompt.ts), so the prose can never claim a count the catalogue does not have.
 *
 * Runs under Node's native type stripping (Node >= 22.18): `node scripts/build-instructions.ts`.
 * It must not import anything from src/ that imports the SDK or zod, because at this point nothing
 * is compiled; the token list below is checked against src/prompt.ts by test/instructions.test.ts.
 */
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const mcpRoot = path.resolve(here, '..');
const repoRoot = path.resolve(mcpRoot, '..');

export const PROMPT_PATH = path.join(repoRoot, 'ai', 'mcp_prompt_ezbookkeeping.md');
export const OUTPUT_PATH = path.join(mcpRoot, 'src', 'instructions.ts');

/** Mirror of PROMPT_TOKENS in src/prompt.ts (the test asserts the two agree). */
export const KNOWN_TOKENS = ['SERVER_KEY', 'TOOL_PREFIX', 'TOTAL_TOOLS', 'READ_TOOLS', 'WRITE_TOOLS', 'CLI_BINARY', 'API_URL', 'CREDENTIALS_FILE', 'APP_URL'];

const LAYER_5_FIRST_SENTENCE = "Is this about the operator's own money kept in **ezBookkeeping** on THIS computer";

export function generate(promptText: string, sourcePath: string): string {
  if (promptText.trim() === '') {
    throw new Error(`${sourcePath} is empty; the instructions block would be empty and the build refuses to ship it`);
  }
  const unknown = new Set<string>();
  for (const m of promptText.matchAll(/\{([A-Z][A-Z0-9_]*)\}/g)) {
    const token = m[1] ?? '';
    if (!KNOWN_TOKENS.includes(token)) {
      unknown.add(token);
    }
  }
  if (unknown.size > 0) {
    throw new Error(`${sourcePath} uses unknown token(s): ${[...unknown].map(t => `{${t}}`).join(', ')}. Known tokens: ${KNOWN_TOKENS.map(t => `{${t}}`).join(', ')}`);
  }
  if (!promptText.trimStart().startsWith(LAYER_5_FIRST_SENTENCE)) {
    throw new Error(`${sourcePath} must begin with the routing sentence of pm/mcp.mdx §3.4 layer 5 ("${LAYER_5_FIRST_SENTENCE} …")`);
  }

  const sha = crypto.createHash('sha256').update(promptText).digest('hex').slice(0, 16);
  const rel = path.relative(mcpRoot, sourcePath).split(path.sep).join('/');

  return [
    '// GENERATED by scripts/build-instructions.ts from ' + rel + ' — do not edit.',
    '// Source sha256 prefix: ' + sha + '. Regenerate with `npm run build` (or `just build`).',
    '// pm/mcp.mdx §8.3: the instructions payload, served in exactly one place — the initialize result.',
    "import { DEFAULT_PROMPT_VALUES, resolveInstructionsFrom, substitute } from './prompt.js';",
    "import type { PromptValues } from './prompt.js';",
    '',
    '/** The prose exactly as ai/mcp_prompt_ezbookkeeping.md holds it, tokens unsubstituted. */',
    'export const PROMPT_SOURCE = ' + JSON.stringify(promptText) + ';',
    '',
    "export const PROMPT_SOURCE_SHA256 = '" + sha + "';",
    '',
    '/** The instructions with the default values; every count comes from the registry. */',
    'export const INSTRUCTIONS = substitute(PROMPT_SOURCE, DEFAULT_PROMPT_VALUES);',
    '',
    '/** The instructions for this process: the EZBKMCP_PROMPT_FILE override if usable, else the generated source. */',
    'export function resolveInstructions(values: PromptValues, promptFile: string | undefined, warn: (line: string) => void): string {',
    '  return resolveInstructionsFrom(PROMPT_SOURCE, values, promptFile, warn);',
    '}',
    '',
  ].join('\n');
}

export function build(): { changed: boolean; output: string } {
  let promptText: string;
  try {
    promptText = fs.readFileSync(PROMPT_PATH, 'utf8');
  } catch (err) {
    throw new Error(`cannot read the instructions prompt ${PROMPT_PATH}: ${(err as Error).message}`);
  }
  const output = generate(promptText, PROMPT_PATH);
  let existing = '';
  try {
    existing = fs.readFileSync(OUTPUT_PATH, 'utf8');
  } catch {
    existing = '';
  }
  if (existing !== output) {
    fs.writeFileSync(OUTPUT_PATH, output, 'utf8');
    return { changed: true, output };
  }
  return { changed: false, output };
}

const invokedDirectly = process.argv[1] !== undefined && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  try {
    const { changed } = build();
    process.stderr.write(`build-instructions: ${changed ? 'wrote' : 'unchanged'} ${path.relative(mcpRoot, OUTPUT_PATH)}\n`);
  } catch (err) {
    process.stderr.write(`build-instructions: ${(err as Error).message}\n`);
    process.exit(1);
  }
}
